--------------------------------------------------------
--  已建立檔案 - 星期二-三月-15-2016   
--------------------------------------------------------
@D:\tmp\proc\ALL_PROCESSORS.sql
@D:\tmp\proc\BATCH_APPROVER_LIST.sql
@D:\tmp\proc\BATCH_COUNT.sql
@D:\tmp\proc\BATCH_COUNT_APPEND.sql
@D:\tmp\proc\BATCH_DAILY_COUNT.sql
@D:\tmp\proc\BATCH_DETAIL_CHECK.sql
@D:\tmp\proc\BATCH_DETAIL_DEFECT.sql
@D:\tmp\proc\BATCH_DETAIL_LIST.sql
@D:\tmp\proc\BATCH_DETAIL_REASON.sql
@D:\tmp\proc\BATCH_HISTROY_LIST.sql
@D:\tmp\proc\BATCH_INFO.sql
@D:\tmp\proc\BATCH_JUDGE.sql
@D:\tmp\proc\BATCH_MONTHLY_FIRST.sql
@D:\tmp\proc\BATCH_MONTHLY_NOT_FIRST.sql
@D:\tmp\proc\BATCH_OUTSOURCING_LIST.sql
@D:\tmp\proc\BATCH_PAYMENT.sql
@D:\tmp\proc\BATCH_PAYMENT_CHECK.sql
@D:\tmp\proc\BATCH_REPORT_COUNT.sql
@D:\tmp\proc\BATCH_REPORT_DETAIL.sql
@D:\tmp\proc\BATCH_REPORT_PREDEFECTS.sql
@D:\tmp\proc\BATCH_SAMPLE.sql
@D:\tmp\proc\BATCH_SEND.sql
@D:\tmp\proc\BATCH_STEP_CODE.sql
@D:\tmp\proc\BATCH_TO_DISPATCH.sql
@D:\tmp\proc\BATCH_TO_POOL.sql
@D:\tmp\proc\CASE_DISPATCH.sql
@D:\tmp\proc\CASE_DIVIDE.sql
@D:\tmp\proc\CASE_FINISH_OTHER_SESSION.sql
@D:\tmp\proc\CASE_LIST.sql
@D:\tmp\proc\CASE_MARK_UNUSUAL.sql
@D:\tmp\proc\CASE_REMOVE_DISPATCH.sql
@D:\tmp\proc\CASE_REMOVE_OVERTIME.sql
@D:\tmp\proc\CASE_REMOVE_POSTPONE.sql
@D:\tmp\proc\CASE_TO_ONLINE.sql
@D:\tmp\proc\CASE_TO_PAPER.sql
@D:\tmp\proc\CASE_TO_POSTPONE.sql
@D:\tmp\proc\CHECK_OVERTIME.sql
@D:\tmp\proc\CHECK_RECEIVE.sql
@D:\tmp\proc\CHECK_RECEIVE_DAY.sql
@D:\tmp\proc\CHECK_STATUS.sql
@D:\tmp\proc\CHECK_UNOVERTIME.sql
@D:\tmp\proc\CHECK_UNPOSTPONE.sql
@D:\tmp\proc\CHIEF_FROM_OTHER_SECTION.sql
@D:\tmp\proc\CHIEF_TO_DISPATCH.sql
@D:\tmp\proc\CHIEF_TO_OTHER_SECTION.sql
@D:\tmp\proc\CHIEF_TO_POOL.sql
@D:\tmp\proc\CHIEF_TO_PROCESSOR.sql
@D:\tmp\proc\DASHBOARD_APPROVER.sql
@D:\tmp\proc\DASHBOARD_CHIEF.sql
@D:\tmp\proc\DASHBOARD_DAIRY_REPORT.sql
@D:\tmp\proc\DASHBOARD_OUTSOURCING.sql
@D:\tmp\proc\DASHBOARD_PERSONAL.sql
@D:\tmp\proc\DASHBOARD_SECTION.sql
@D:\tmp\proc\DISPATCH_RCL_APPLS.sql
@D:\tmp\proc\DISPATCH_RCL_APPLS_ORI.sql
@D:\tmp\proc\ERROR_REPORT_CHANGE_STATUS.sql
@D:\tmp\proc\ERROR_REPORT_LIST.sql
@D:\tmp\proc\ERROR_REPORT_LIST_APPROVER.sql
@D:\tmp\proc\ERROR_REPORT_REDO.sql
@D:\tmp\proc\ERROR_REPORT_SAVE.sql
@D:\tmp\proc\GET_ANNEX.sql
@D:\tmp\proc\GET_BATCH.sql
@D:\tmp\proc\GET_BATCH_DAY.sql
@D:\tmp\proc\GET_BATCH_HR.sql
@D:\tmp\proc\GET_DIRECT_PAGE.sql
@D:\tmp\proc\GET_PROCCESS_PAGE.sql
@D:\tmp\proc\GET_PUBLIC_BIBLIOGRAPHY.sql
@D:\tmp\proc\GET_RECEIVE.sql
@D:\tmp\proc\LIST_CASE_SECTION.sql
@D:\tmp\proc\LIST_CHEK_RECEIVE.sql
@D:\tmp\proc\LIST_DAIRY_REPORT.sql
@D:\tmp\proc\LIST_PERFORMANCE.sql
@D:\tmp\proc\LIST_RECEIVE_TRANS_LOG.sql
@D:\tmp\proc\LIST_RECEIVE_TRANS_LOG_INFO.sql
@D:\tmp\proc\LIST_SECTION.sql
@D:\tmp\proc\LIST_SECTION_UNSIGN.sql
@D:\tmp\proc\LIST_VIEW.sql
@D:\tmp\proc\PROCESSOR_TO_PROCESSOR.sql
@D:\tmp\proc\QUOTA_MAIN.sql
@D:\tmp\proc\QUOTA_SAVE.sql
@D:\tmp\proc\RECEIVE_RESET_APPLNO.sql
@D:\tmp\proc\RECEIVE_TRANSFER.sql
@D:\tmp\proc\RECEIVE193.sql
@D:\tmp\proc\REQUEST_FOR_IMAGES.sql
@D:\tmp\proc\RESET_EARLY_APPLS.sql
@D:\tmp\proc\RESET_INFO_APPLS.sql
@D:\tmp\proc\RESET_INFO_APPLS_1.sql
@D:\tmp\proc\SAVE_ANNEX.sql
@D:\tmp\proc\SAVE_APPL_EXAM.sql
@D:\tmp\proc\SAVE_BIOMATERIAL.sql
@D:\tmp\proc\SAVE_DIRECT_PAGE.sql
@D:\tmp\proc\SAVE_GRACE_PERIOD.sql
@D:\tmp\proc\SAVE_MATERIAL_APPL_DATE.sql
@D:\tmp\proc\SAVE_MERGE_RECEIVE.sql
@D:\tmp\proc\SAVE_PRIORITY_RIGHT.sql
@D:\tmp\proc\SAVE_PROCCESS_PAGE.sql
@D:\tmp\proc\SAVE_SPT31B_PRE_DATE.sql
@D:\tmp\proc\SEND_APPL_TO_EARLY_PUBLICATION.sql
@D:\tmp\proc\SEND_APPL_TO_PROCEDURE.sql
@D:\tmp\proc\SKILL_LIST.sql
@D:\tmp\proc\SKILL_PRELOAD.sql
@D:\tmp\proc\SKILL_UPDATE.sql
@D:\tmp\proc\UPDATE_EARLY_STATUS.sql
@D:\tmp\proc\USER_IS_MIS.sql
@D:\tmp\proc\USER_TO_190.sql
@D:\tmp\proc\VALIDATE_BIOMATERIAL.sql
@D:\tmp\proc\VALIDATE_GRACE_PERIOD.sql
@D:\tmp\proc\VALIDATE_PRIORITY_RIGHT.sql
